version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx-config/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "3001:3001"
    links:
     - like-ipfs
     - like-server
  like-ipfs:
    image: ipfs/go-ipfs
    ports:
     - "5001:5001"
     - "4001:4001"
     - "8080:8080"
    volumes:
     - ./ipfs:/data/ipfs
  like-server:
    build: .
    volumes:
     - ./server.js:/app/server.js
     - ./config:/app/config
    links:
     - like-ipfs
