version: '3'
services:
  like-ipfs:
    image: ipfs/go-ipfs
    ports:
     - "5001:5001"
     - "4001:4001"
     - "8080:8080"
    volumes:
     - ./ipfs:/data/ipfs
  like-server:
    build: .
    ports:
     - "3001:3001"
    volumes:
     - .:/app
    links:
     - like-ipfs
