apiVersion: v1
kind: Service
metadata:
  name: ipfs
  namespace: default
  labels:
    app: ipfs
spec:
  ports:
  - port: 4001
    name: swarm
  - port: 8080
    name: readonly
  selector:
    app: ipfs
  type: LoadBalancer
  loadBalancerIP: 35.197.97.176

---

apiVersion: v1
kind: Service
metadata:
  name: ipfs-api
  namespace: default
  labels:
    app: ipfs
spec:
  ports:
  - port: 5001
    name: api
  selector:
    app: ipfs

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ipfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
        - image: ipfs/go-ipfs:latest
          name: ipfs
          ports:
            - containerPort: 4001
              name: swarm
            - containerPort: 5001
              name: api
            - containerPort: 8080
              name: readonly
          resources:
            requests:
              cpu: "0.05"
          volumeMounts:
            - name: ipfs-disk
              mountPath: "/data/ipfs"
      volumes:
      - name: ipfs-disk
        # This GCE PD must already exist.
        gcePersistentDisk:
          pdName: ipfs-disk
          fsType: ext4

